#!/bin/bash

echo "SmartWealth AI Data Pipelines - Environment Setup"
echo "=================================================="
echo ""
echo "To activate the virtual environment, run:"
echo "source venv/bin/activate"
echo ""
echo "To deactivate the virtual environment, run:"
echo "deactivate"
echo ""
echo "Installed packages:"
echo "- pandas 2.3.2"
echo "- yfinance 0.2.65"
echo "- requests 2.32.5"
echo "- pydantic 2.11.7"
echo "- pydantic-settings 2.10.1"
echo "- typer 0.16.1"
echo "- python-dotenv 1.1.1"
echo ""
echo "All packages are compatible with Python 3.13 and have been tested."
